DROP DATABASE IF EXISTS SUPPORT_TELCO;

CREATE DATABASE SUPPORT_TELCO;
USE SUPPORT_TELCO;


CREATE TABLE users(
    id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    username VARCHAR(16) NOT NULL,
    password VARCHAR(60) NOT NULL,
    fullname VARCHAR(100) NOT NULL
);

CREATE TABLE EquiposTelco (
    Id_ActivoTx CHAR(15) PRIMARY KEY NOT NULL UNIQUE,
    Serial_EqTx VARCHAR(15) NOT NULL UNIQUE,
    Mac_EqTx CHAR(20) UNIQUE,
    Modelo_EqTx VARCHAR(30) NOT NULL,
    Marca_EqTx VARCHAR(20) NOT NULL,
    Description_EqTx VARCHAR(100) NOT NULL,
    Propietario_EqTx VARCHAR(20) NOT NULL,
    Ubicación_EqTx VARCHAR(40) NOT NULL,
    user_id INT(11),
    Created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id)
);


CREATE TABLE HERRAMIENTA__BODEGA (
    Id_activoH CHAR(15) PRIMARY KEY NOT NULL UNIQUE,
    Serial_H VARCHAR(15) NOT NULL UNIQUE,	
    Modelo_H VARCHAR(15) NOT NULL,   	
    Marca_H	VARCHAR(15) NOT NULL,
    Description_H VARCHAR(100) NOT NULL,	
    Propietario_H VARCHAR(20) NOT NULL,	
    Ubicación_H	VARCHAR(40) ,
    Observaciones_H VARCHAR(40) NOT NULL,
    Created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    
);

CREATE TABLE CONSUMIBLES__BODEGA (
    Id_Consumible CHAR(15) PRIMARY KEY NOT NULL UNIQUE,	
    Referencia_C VARCHAR(15) NOT NULL,	
    Description_C VARCHAR(100) NOT NULL,
    Marca_C	VARCHAR(20) NOT NULL,
    Propietario_C VARCHAR(20) NOT NULL,	
    Ubicación_C	VARCHAR(100) ,
    Imagen_C VARCHAR(100) ,
    Created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);







CREATE TABLE users ( 
    
)

ALTER TABLE equipostelco MODIFY Modelo_EqTx VARCHAR(30);

-- cambiar el nombre o renombrar una columna
ALTER TABLE equipostelco CHANGE propietario_EqTx Propietario_EqTx VARCHAR(20);
